/* Naseej — authoritative product index for server-side validation.
 *
 * This is the single source of truth the Cloud Functions use to decide whether
 * a threadId / waypointId / branchId is real. The numbers come from js/data.js
 * (generated by running: node -e "..." — see the comment in scripts/build.cjs).
 *
 * Do NOT add branch/waypoint data here by hand — regenerate it whenever
 * js/data.js changes, using the snippet at the bottom of this file.
 *
 * Validation rule: a threadId must be a key in THREADS; a waypointId must
 * appear in the array at THREADS[threadId]; a branchId must appear in
 * BRANCHES[threadId] (only threads that have branch options have an entry).
 */

/* Thread → valid waypoint id list (positive integers, 1-based). */
const THREADS = {
  1:  [1, 2, 3, 4, 5],
  2:  [1, 2, 3, 4, 5, 6],
  3:  [1, 2, 3, 4],
  4:  [1, 2, 3, 4],
  5:  [1, 2, 3, 4, 5],
  6:  [1, 2, 3, 4, 5],
  7:  [1, 2, 3, 4, 5],
  8:  [1, 2, 3, 4],
  9:  [1, 2, 3, 4, 5],
  10: [1, 2, 3, 4],
  11: [1, 2, 3, 4],
  12: [1, 2, 3, 4],
  13: [1, 2, 3, 4],
  14: [1, 2, 3, 4],
  15: [1, 2, 3, 4],
  16: [1, 2, 3, 4],
  17: [1, 2, 3, 4],
  18: [1, 2, 3],
  19: [1, 2, 3, 4],
  20: [1, 2, 3, 4],
  21: [1, 2, 3],
  22: [1, 2, 3, 4],
  23: [1, 2, 3],
  24: [1, 2, 3, 4, 5],
  25: [1, 2, 3, 4],
  26: [1, 2, 3, 4],
  27: [1, 2, 3],
};

/* Thread → valid branch ids. Only threads that support branching have an entry.
 * Thread 10 is the Yarmouk living-mystery thread. */
const BRANCHES = {
  10: ['person', 'object'],
};

/* ─── Helpers ────────────────────────────────────────────────────────────────── */

/**
 * Returns true when threadId is a valid, known thread.
 * threadId must be a finite positive integer.
 */
function isValidThread(threadId) {
  if (typeof threadId !== 'number' || !Number.isFinite(threadId) ||
      Math.floor(threadId) !== threadId || threadId <= 0) return false;
  return Object.prototype.hasOwnProperty.call(THREADS, threadId);
}

/**
 * Returns true when waypointId belongs to the given thread.
 * Pass waypointId === null to validate a thread-level (non-waypoint) progress row.
 */
function isValidWaypoint(threadId, waypointId) {
  if (!isValidThread(threadId)) return false;
  if (waypointId === null || waypointId === undefined) return true; // thread-level row
  if (typeof waypointId !== 'number' || !Number.isFinite(waypointId) ||
      Math.floor(waypointId) !== waypointId || waypointId <= 0) return false;
  return THREADS[threadId].indexOf(waypointId) !== -1;
}

/**
 * Returns true when branchId is an allowed choice for the given thread.
 */
function isValidBranch(threadId, branchId) {
  if (!isValidThread(threadId)) return false;
  if (!Object.prototype.hasOwnProperty.call(BRANCHES, threadId)) return false;
  if (typeof branchId !== 'string' || !branchId) return false;
  return BRANCHES[threadId].indexOf(branchId) !== -1;
}

/**
 * Returns the list of allowed branch ids for a thread, or null if the thread
 * does not support branching.
 */
function allowedBranches(threadId) {
  if (!isValidThread(threadId)) return null;
  return BRANCHES[threadId] || null;
}

module.exports = {
  THREADS,
  BRANCHES,
  isValidThread,
  isValidWaypoint,
  isValidBranch,
  allowedBranches,
};
